version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: issue-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: issue_tracker
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123321
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
